### ISSUE TITLE
Implement basic sync

### ISSUE THREAD

**Issue by lemon24** [lemon24/smalltsdb#2]
As of fc5ea2cae9d8978409a03b3fa5104a310210e6dd, we're using ViewTSDB with both the web app and the daemon, since TablesTSDB.sync() does a full sync every time and does not delete any datapoints.

With about 140K datapoints over 29 metrics, ViewTSDB.list_metrics() started to be unbearable. As expected, TablesTDSB.sync() takes about as much, since it has to cycle through the same data in the same way.

As it can be seen from the timings below, it's not the number of `incoming` datapoints that kills it, but the number of aggregated datapoints that have data; `onehour` is better than `fiveminute` is better than `oneminute`; `oneminute` took roughly the same as `tensecond`, however, since datapoints were coming in roughly once a minute.

```
>>> from smalltsdb.tsdb import ViewTSDB                                         
>>> db = ViewTSDB('db.sqlite')                                                  
>>> %timeit -n1 -r1 list(db.list_metrics())                                     
4min 2s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

```
>>> from smalltsdb.tsdb import TablesTSDB                                       
>>> db = TablesTSDB('db.sqlite')                                                
>>> %timeit -n1 -r1 db.sync()                                                   
DEBUG:smalltsdb:synced onesecond in 0:01:32.920555
DEBUG:smalltsdb:synced tensecond in 0:01:15.686526
DEBUG:smalltsdb:synced oneminute in 0:01:22.030431
DEBUG:smalltsdb:synced fiveminute in 0:00:15.129802
DEBUG:smalltsdb:synced onehour in 0:00:01.969328
DEBUG:smalltsdb:synced oneday in 0:00:00.840914
4min 28s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
>>> %timeit -n1 -r1 list(db.list_metrics())                                     
148 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

```
sqlite> select count(*) from incoming;
146543
sqlite> select count(distinct path) from incoming;
29
sqlite> select count(*) from onesecond;
146525
sqlite> select count(*) from tensecond;
146499
sqlite> select count(*) from oneminute;
146459
sqlite> select count(*) from fiveminute;
29484
sqlite> select count(*) from onehour;
2494
sqlite> select count(*) from oneday;
146
```

**Comment by lemon24** [comment]
1d99c7c results in the same sync() time, both on the first and subsequent runs. I assume this is because `select from incoming` always does a full table scan and we're not deleting any data yet, so it has to scan the same amount as the first time (several days). Creating an index on `incoming(path, timestamp)` should help, but it doesn't seem to.

**Comment by lemon24** [comment]
After a60a3f7:

```
>>> %timeit -n1 -r1 db.sync()   
4min 21s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
>>> %timeit -n1 -r1 list(db.list_metrics())                                                                                                                                                                 
126 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
>>> %timeit -n1 -r1 db.sync()                                                                                                                                                                               
1.47 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

**Comment by lemon24** [comment]
After 7cc4328 I started seeing sqlite3.OperationalError "database is locked" in the daemon logs "database is locked" and "database or disk is full" in the sync logs.

The first sync seems to have run; after that the syncs take a lot due to the "last finals" query (haven't had one finish yet, after ~10 minutes).

**Comment by lemon24** [comment]
Ok, dcbdca0 seems to have fixed it.

**Comment by lemon24** [comment]
It died overnight.

The daemon is still going; sync fails:

```
DEBUG:smalltsdb:getting onesecond last finals
DEBUG:smalltsdb:syncing onesecond host.cpu.load for [2019-11-03 09:03:02, 2019-11-03 09:04:01)
...
DEBUG:smalltsdb:synced onesecond in 0:00:01.563083
DEBUG:smalltsdb:getting tensecond last finals
DEBUG:smalltsdb:syncing tensecond host.cpu.load for [2019-11-03 08:27:10, 2019-11-03 09:01:00)
Traceback (most recent call last):
  ...
  File "/apps/smalltsdb/lib/python3.6/site-packages/smalltsdb/cli.py", line 32, in sync
    smalltsdb.TSDB(kwargs['path']).sync()
  File "/apps/smalltsdb/lib/python3.6/site-packages/smalltsdb/tsdb.py", line 333, in sync
    {'path': path, 'start': final_start, 'end': final_end},
sqlite3.OperationalError: database is locked
```

Sometimes it makes it to `syncing oneminute`, sometimes only to `syncing tensecond`.

Running sync on a copy of the database took ~10 seconds.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2707033/68082740-e2479600-fe28-11e9-8bbf-3492d7b21721.png">

Update: 

I confirmed only daemon and sync are using the database file at any given time. Stopping the daemon temporarily let sync finish.

Not sure why sync would fail, though; in theory, the daemon should keep the database locked only while it inserts new datapoints, and that should take much less than the 5 seconds timeout. Time to give https://beets.io/blog/sqlite-nightmare.html a re-read.

Update #2: ~~`pragma compile_options` does not return `HAVE_USLEEP` on this machine.~~ It's not easy to check if HAVE_USLEEP is enabled, as it doesn't always show up; see beetbox/beets#2241.

~~Update #3: While trying to compile SQLite, I added 1GB swap to the existing .46GB memory. With it, `sync` never fails (why?!).~~ It still fails.

Update #4:

~~Using a libsqlite3.so compiled with HAVE_USLEEP also results in `sync` never failing (no swap).~~ It still fails.

While testing this, I noticed `sync` can fails with "database is locked" in ~2 seconds, much less than the busy_timeout of 5 seconds.

Update #5:

This may be because the [`last_finals` query](https://github.com/lemon24/smalltsdb/blob/9af610de356eed1b9298521daec8a75ba7da7370/src/smalltsdb/tsdb.py#L285) is not fully consumed when we update the aggregation tables (which it uses). Consuming it before any of the inserts (`last_finals = list(last_finals)`) seems to fix it.

**Comment by lemon24** [comment]
OK, I found the issue (after improving logging; graphs below):

* At some point after reboot, `sync` uses up all the [I/O credits](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html#IOcredit) on my gp2 4GB EBS volume, which results in it reverting to baseline performance.
* This causes `sync`s to take much, much longer than 1 minute (from 10s to over 300s), and causes high load and decreased available memory.
* In turn, this results in locks being held on the database for longer, which increases the likelihood of timeouts for `daemon` ("database is locked").
* It also results in `sync` overlapping with itself, since it runs on a 1-minute cron.

There is another issue of the OOM killer kicking in at a later point. I'm not sure this is caused by the first one; it may be caused by the host simply having too little memory overall, but the available memory does drop once the I/O performance degrades.

There are multiple things that can make this better:

* Don't do full table scans on a 200 MB database each minute. This is probably what's eating up the I/O credits. From the logs below, it looks like the "last finals" query is the main culprit (it takes up the most time). Indexes would probably help. Alternatively, we could just store the last finals on a separate table, but this requires additional code.
* Don't run more than one sync (a `--lock-file` option has already been implemented in b96f9f7).
* Don't sync periods >oneminute every minute.
* Increase the daemon timeout (should give it a better chance of getting to the database, maybe).
* Disk metrics would have probably made the issue easier to spot.

---

These graphs cover time from 08:00 to 16:00; a reboot happened at ~8:50. The database size is roughly 200 MB.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/2707033/68807565-b8843f80-0670-11ea-9b6b-8a36e04e0e0c.png">

![host cpu utilization](https://user-images.githubusercontent.com/2707033/68807579-bfab4d80-0670-11ea-9981-b81caeb1950d.png)

![host cpu load](https://user-images.githubusercontent.com/2707033/68807594-c5a12e80-0670-11ea-873b-3dd039a9bd0b.png)

![host mem available](https://user-images.githubusercontent.com/2707033/68807619-d2be1d80-0670-11ea-972c-81bcb6c5bba3.png)

![smalltsdb daemon error](https://user-images.githubusercontent.com/2707033/68807632-d782d180-0670-11ea-9643-979675280bb8.png)

sync.log:

```
2019-11-13T08:54:01 18620 DEBUG   timing start: sync all
2019-11-13T08:54:01 18620 DEBUG   timing start: sync last finals: onesecond
2019-11-13T08:54:04 18620 DEBUG   timing end (3.22s): sync last finals: onesecond
2019-11-13T08:54:04 18620 DEBUG   timing start: sync last finals: tensecond
2019-11-13T08:54:07 18620 DEBUG   timing end (2.86s): sync last finals: tensecond
2019-11-13T08:54:07 18620 DEBUG   timing start: sync last finals: oneminute
2019-11-13T08:54:10 18620 DEBUG   timing end (2.69s): sync last finals: oneminute
2019-11-13T08:54:10 18620 DEBUG   timing start: sync last finals: fiveminute
2019-11-13T08:54:11 18620 DEBUG   timing end (0.56s): sync last finals: fiveminute
2019-11-13T08:54:11 18620 DEBUG   timing start: sync last finals: onehour
2019-11-13T08:54:11 18620 DEBUG   timing end (0.05s): sync last finals: onehour
2019-11-13T08:54:11 18620 DEBUG   timing start: sync last finals: oneday
2019-11-13T08:54:11 18620 DEBUG   timing end (0.01s): sync last finals: oneday
2019-11-13T08:54:11 18620 DEBUG   timing end (10.24s): sync all
2019-11-13T08:54:11 18620 DEBUG   sync probably done, maxrss: 0.06 MiB
... it keeps going at ~10s per run, and then
2019-11-13T13:54:01 24148 DEBUG   timing start: sync all
2019-11-13T13:54:01 24148 DEBUG   timing start: sync last finals: onesecond
2019-11-13T13:54:04 24148 DEBUG   timing end (3.00s): sync last finals: onesecond
2019-11-13T13:54:05 24148 DEBUG   timing start: sync last finals: tensecond
2019-11-13T13:54:07 24148 DEBUG   timing end (2.88s): sync last finals: tensecond
2019-11-13T13:54:07 24148 DEBUG   timing start: sync last finals: oneminute
2019-11-13T13:54:10 24148 DEBUG   timing end (2.76s): sync last finals: oneminute
2019-11-13T13:54:10 24148 DEBUG   timing start: sync last finals: fiveminute
2019-11-13T13:54:19 24148 DEBUG   timing end (8.94s): sync last finals: fiveminute
2019-11-13T13:54:19 24148 DEBUG   timing start: sync last finals: onehour
2019-11-13T13:54:21 24148 DEBUG   timing end (1.15s): sync last finals: onehour
2019-11-13T13:54:21 24148 DEBUG   timing start: sync last finals: oneday
2019-11-13T13:54:21 24148 DEBUG   timing end (0.01s): sync last finals: oneday
2019-11-13T13:54:21 24148 DEBUG   timing end (19.30s): sync all
2019-11-13T13:54:21 24148 DEBUG   sync probably done, maxrss: 0.06 MiB
2019-11-13T13:55:01 24271 DEBUG   timing start: sync all
2019-11-13T13:55:01 24271 DEBUG   timing start: sync last finals: onesecond
2019-11-13T13:55:36 24271 DEBUG   timing end (34.88s): sync last finals: onesecond
2019-11-13T13:55:36 24271 DEBUG   timing start: sync last finals: tensecond
2019-11-13T13:56:01 24401 DEBUG   timing start: sync all
2019-11-13T13:56:06 24401 DEBUG   timing end (5.01s): sync all
2019-11-13T13:56:06 24401 DEBUG   sync probably done, maxrss: 0.03 MiB
Traceback (most recent call last):
sqlite3.OperationalError: database is locked
2019-11-13T13:56:53 24271 DEBUG   timing end (76.25s): sync last finals: tensecond
2019-11-13T13:56:53 24271 DEBUG   timing start: sync last finals: oneminute
2019-11-13T13:57:01 24527 DEBUG   timing start: sync all
2019-11-13T13:57:01 24527 DEBUG   timing start: sync last finals: onesecond
2019-11-13T13:58:01 24654 DEBUG   timing start: sync all
2019-11-13T13:58:06 24654 DEBUG   timing end (5.01s): sync all
2019-11-13T13:58:06 24654 DEBUG   sync probably done, maxrss: 0.03 MiB
Traceback (most recent call last):
sqlite3.OperationalError: database is locked
2019-11-13T13:59:01 24773 DEBUG   timing start: sync all
2019-11-13T13:59:06 24773 DEBUG   timing end (5.01s): sync all
2019-11-13T13:59:06 24773 DEBUG   sync probably done, maxrss: 0.03 MiB
Traceback (most recent call last):
sqlite3.OperationalError: database is locked
2019-11-13T13:59:20 24271 DEBUG   timing end (146.34s): sync last finals: oneminute
2019-11-13T13:59:25 24271 DEBUG   timing end (263.30s): sync all
2019-11-13T13:59:25 24271 DEBUG   sync probably done, maxrss: 0.06 MiB
... followed by more hundred-second runs interleaved with "database is locked"
```

**Comment by lemon24** [comment]
Tried creating an index on oneminute(path, timestamp). It gets used, but on my Mac it doesn't improve the query time (it's very fast to begin with); [this answer](https://serverfault.com/a/954175) shows one way of simulating a slow disk.

**Comment by lemon24** [comment]
After using `(path, timestamp)` indexes on both the aggregate and incoming tables, the number of read operations decreased significantly (from ~450 to ~30 per second), with the write operations only doubling. This puts I/O credit usage in the green (the burst balance is not decreasing anymore). CPU utilization also decreased from 11% to 4%.

All graphs are from 21:13 to 22:13. The aggregate index was deployed around 21:35, the incoming index around 22:06.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/2707033/68901626-f059b880-073e-11ea-8e7e-a5e9f2d50ed3.png">

![host disk nvme0n1 r_s](https://user-images.githubusercontent.com/2707033/68901921-9dcccc00-073f-11ea-809d-13b27940d1c6.png)
![host disk nvme0n1 w_s](https://user-images.githubusercontent.com/2707033/68901942-a8876100-073f-11ea-9a0c-f8dd33c17683.png)
![host cpu utilization](https://user-images.githubusercontent.com/2707033/68901949-afae6f00-073f-11ea-8352-20424c5e7278.png)
![host disk nvme0n1 rkb_s](https://user-images.githubusercontent.com/2707033/68901956-b63ce680-073f-11ea-813d-0d1e3ac3e4f9.png)
![host disk nvme0n1 wkb_s](https://user-images.githubusercontent.com/2707033/68901962-bc32c780-073f-11ea-93be-befa55bde779.png)

**Comment by lemon24** [comment]
Uh oh (graphs below).

Update: Most likely this is due to adding new metrics (https://github.com/lemon24/owncloud/commit/12fa4db85cccbf4b3fb91a1d6cf4ac2edd6a3016); a bunch of bogus metrics got created too (#3), which may slow things even more.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/2707033/69028671-5a8e8980-09db-11ea-8aca-48b24c70dfa5.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/2707033/69028747-9c1f3480-09db-11ea-8d12-c881511c1947.png">
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2707033/69028786-bf49e400-09db-11ea-9f77-bf3e4c6216fe.png">
